version: '3.8'

services:
  alura-space:
    container_name: alura-space
    image: alura-space-image
    build:
      context: .
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true